export interface CarModel {
  slug: string;
  name: string;
  category: "SUV" | "MPV" | "Pickup";
  tagline: string;
  price: string;
  priceNum: number;
  image: string;
  heroImage: string;
  engine: string;
  transmission: string;
  seats: string;
  power: string;
  torque: string;
  fuel: string;
  topSpeed: string;
  acceleration: string;
  features: string[];
  highlights: { icon: string; label: string; value: string }[];
  colors: { name: string; hex: string }[];
  variants: { name: string; price: string }[];
  description: string;
  warranty: string;
}

export const cars: CarModel[] = [
  {
    slug: "xpander",
    name: "Xpander",
    category: "MPV",
    tagline: "The Ultimate Family MPV",
    price: "Mulai Rp 270 Juta",
    priceNum: 270,
    image: "/images/xpander.png",
    heroImage: "/images/xpander.png",
    engine: "1.5L DOHC 16V MIVEC",
    transmission: "5MT & CVT",
    seats: "7 Penumpang",
    power: "105 PS",
    torque: "141 Nm",
    fuel: "Bensin",
    topSpeed: "170 km/h",
    acceleration: "12.5 detik",
    features: [
      "Multi Around Monitor",
      "Auto Emergency Braking",
      "Forward Collision Mitigation",
      "8\" Touchscreen Head Unit",
      "Keyless Operation System",
      "Push Start Button",
      "Dual SRS Airbag",
      "ABS + EBD",
      "Active Stability Control",
      "Hill Start Assist",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "1.5L MIVEC" },
      { icon: "fuel", label: "BBM", value: "12.4 km/L" },
      { icon: "seat", label: "Kapasitas", value: "7 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Sterling Silver", hex: "#c0c0c0" },
      { name: "Grayish Blue", hex: "#6b7d8d" },
    ],
    variants: [
      { name: "Xpander GLX MT", price: "Rp 270 Juta" },
      { name: "Xpander GLX CVT", price: "Rp 285 Juta" },
      { name: "Xpander Exceed CVT", price: "Rp 305 Juta" },
      { name: "Xpander Ultimate CVT", price: "Rp 325 Juta" },
    ],
    description: "Mitsubishi Xpander — MPV keluarga terbaik dengan kabin luas 7 penumpang, konsumsi BBM irit, dan teknologi keselamatan terdepan. Desain Dynamic Shield yang modern dan tangguh membuat Xpander menjadi pilihan utama keluarga Indonesia.",
    warranty: "3 Tahun / 100.000 km",
  },
  {
    slug: "xpander-cross",
    name: "Xpander Cross",
    category: "MPV",
    tagline: "Adventure Meets Family",
    price: "Mulai Rp 331 Juta",
    priceNum: 331,
    image: "/images/xpander-cross.png",
    heroImage: "/images/xpander-cross.png",
    engine: "1.5L DOHC 16V MIVEC",
    transmission: "CVT",
    seats: "7 Penumpang",
    power: "105 PS",
    torque: "141 Nm",
    fuel: "Bensin",
    topSpeed: "170 km/h",
    acceleration: "12.8 detik",
    features: [
      "Multi Around Monitor",
      "Auto Emergency Braking",
      "Forward Collision Mitigation",
      "9\" Touchscreen Head Unit",
      "Keyless Operation System",
      "Push Start Button",
      "Dual Zone AC",
      "Roof Rail",
      "Ground Clearance 225mm",
      "Active Stability Control",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "1.5L MIVEC" },
      { icon: "fuel", label: "BBM", value: "11.8 km/L" },
      { icon: "seat", label: "Kapasitas", value: "7 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Sunrise Orange", hex: "#e87f24" },
      { name: "Grayish Blue", hex: "#6b7d8d" },
    ],
    variants: [
      { name: "Xpander Cross CVT", price: "Rp 331 Juta" },
      { name: "Xpander Cross Exceed CVT", price: "Rp 350 Juta" },
      { name: "Xpander Cross Ultimate CVT", price: "Rp 370 Juta" },
    ],
    description: "Xpander Cross menghadirkan tampilan SUV sporty dengan ground clearance lebih tinggi 225mm, roof rail, dan desain yang lebih tangguh. Sempurna untuk keluarga yang suka petualangan tanpa mengorbankan kenyamanan.",
    warranty: "3 Tahun / 100.000 km",
  },
  {
    slug: "pajero-sport",
    name: "Pajero Sport",
    category: "SUV",
    tagline: "Born to Rule The Road",
    price: "Mulai Rp 578 Juta",
    priceNum: 578,
    image: "/images/pajero-sport.png",
    heroImage: "/images/pajero-sport.png",
    engine: "2.4L Diesel Turbo MIVEC",
    transmission: "6MT & 8AT",
    seats: "7 Penumpang",
    power: "181 PS",
    torque: "430 Nm",
    fuel: "Diesel",
    topSpeed: "190 km/h",
    acceleration: "9.8 detik",
    features: [
      "Super Select 4WD-II",
      "Multi Around Monitor",
      "Ultrasonic Misaccel Prevention",
      "Forward Collision Mitigation",
      "8AT with Sports Mode",
      "9\" Touchscreen",
      "Power Tailgate",
      "Dual Zone Auto AC",
      "7 Airbags",
      "Active Stability Control",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "2.4L Diesel" },
      { icon: "fuel", label: "BBM", value: "13.2 km/L" },
      { icon: "seat", label: "Kapasitas", value: "7 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Quartz Brown", hex: "#6b4226" },
      { name: "Sterling Silver", hex: "#c0c0c0" },
    ],
    variants: [
      { name: "Pajero Sport GLX MT 4x2", price: "Rp 578 Juta" },
      { name: "Pajero Sport GLX AT 4x2", price: "Rp 598 Juta" },
      { name: "Pajero Sport Dakar AT 4x2", price: "Rp 638 Juta" },
      { name: "Pajero Sport Dakar AT 4x4", price: "Rp 698 Juta" },
    ],
    description: "Pajero Sport — SUV tangguh dengan performa diesel bertenaga 181 PS dan torsi 430 Nm. Dilengkapi Super Select 4WD-II untuk segala medan, transmisi 8AT, dan kabin premium 7 penumpang. Raja jalan Indonesia.",
    warranty: "3 Tahun / 100.000 km",
  },
  {
    slug: "xforce",
    name: "Xforce",
    category: "SUV",
    tagline: "Unstoppable Style",
    price: "Mulai Rp 388 Juta",
    priceNum: 388,
    image: "/images/outlander.png",
    heroImage: "/images/outlander.png",
    engine: "1.5L DOHC 16V MIVEC",
    transmission: "CVT",
    seats: "5 Penumpang",
    power: "105 PS",
    torque: "141 Nm",
    fuel: "Bensin",
    topSpeed: "175 km/h",
    acceleration: "12.2 detik",
    features: [
      "Multi Around Monitor",
      "Auto Emergency Braking",
      "Forward Collision Mitigation",
      "9\" Touchscreen Wireless Apple CarPlay",
      "Keyless Operation System",
      "Push Start Button",
      "Dual Zone Auto AC",
      "7 Airbags",
      "Active Stability Control",
      "Hill Start Assist",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "1.5L MIVEC" },
      { icon: "fuel", label: "BBM", value: "14.2 km/L" },
      { icon: "seat", label: "Kapasitas", value: "5 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Brilliant Blue", hex: "#2d5da1" },
      { name: "Sunrise Orange", hex: "#e87f24" },
    ],
    variants: [
      { name: "Xforce GLS CVT", price: "Rp 388 Juta" },
      { name: "Xforce Exceed CVT", price: "Rp 418 Juta" },
      { name: "Xforce Ultimate CVT", price: "Rp 448 Juta" },
    ],
    description: "Mitsubishi Xforce — Compact SUV stylish dengan desain Dynamic Shield yang berani. Teknologi terkini termasuk Multi Around Monitor, wireless Apple CarPlay, dan keselamatan terdepan di kelasnya.",
    warranty: "3 Tahun / 100.000 km",
  },
  {
    slug: "destinator",
    name: "Destinator",
    category: "SUV",
    tagline: "Power Your Journey",
    price: "Mulai Rp 385 Juta",
    priceNum: 385,
    image: "/images/outlander.png",
    heroImage: "/images/outlander.png",
    engine: "1.5L Turbo MIVEC",
    transmission: "CVT",
    seats: "7 Penumpang",
    power: "150 PS",
    torque: "250 Nm",
    fuel: "Bensin",
    topSpeed: "185 km/h",
    acceleration: "10.5 detik",
    features: [
      "Multi Around Monitor",
      "Auto Emergency Braking",
      "Forward Collision Mitigation",
      "9\" Touchscreen",
      "Keyless Operation System",
      "Push Start Button",
      "3-Row 7-Seater",
      "Dual Zone Auto AC",
      "7 Airbags",
      "Active Stability Control",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "1.5L Turbo" },
      { icon: "fuel", label: "BBM", value: "12.8 km/L" },
      { icon: "seat", label: "Kapasitas", value: "7 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Graphite Gray", hex: "#5a5a5a" },
      { name: "Brilliant Blue", hex: "#2d5da1" },
    ],
    variants: [
      { name: "Destinator GLS CVT", price: "Rp 385 Juta" },
      { name: "Destinator Exceed CVT", price: "Rp 415 Juta" },
      { name: "Destinator Ultimate CVT", price: "Rp 450 Juta" },
    ],
    description: "Destinator — SUV 7-seater turbocharged untuk keluarga modern. Dengan mesin 1.5L Turbo 150 PS, kabin luas 3 baris, dan teknologi keselamatan lengkap. Performa tangguh, kenyamanan premium.",
    warranty: "3 Tahun / 100.000 km",
  },
  {
    slug: "triton",
    name: "Triton",
    category: "Pickup",
    tagline: "Engineered Beyond Tough",
    price: "Mulai Rp 307 Juta",
    priceNum: 307,
    image: "/images/triton.png",
    heroImage: "/images/triton.png",
    engine: "2.4L Turbo Diesel MIVEC",
    transmission: "6MT & 6AT",
    seats: "2-5 Penumpang",
    power: "181 PS",
    torque: "430 Nm",
    fuel: "Diesel",
    topSpeed: "180 km/h",
    acceleration: "10.2 detik",
    features: [
      "Super Select 4WD",
      "Jet Thrust Fin",
      "Multi Around Monitor",
      "Ultrasonic Misaccel Prevention",
      "Forward Collision Mitigation",
      "8\" Touchscreen",
      "7 Airbags",
      "Active Stability Control",
      "Hill Descent Control",
      "Rear Differential Lock",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "2.4L Turbo Diesel" },
      { icon: "fuel", label: "BBM", value: "12.5 km/L" },
      { icon: "seat", label: "Kapasitas", value: "2-5 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Quartz Brown", hex: "#6b4226" },
      { name: "Sterling Silver", hex: "#c0c0c0" },
    ],
    variants: [
      { name: "Triton GLX MT 4x2", price: "Rp 307 Juta" },
      { name: "Triton GLX AT 4x2", price: "Rp 327 Juta" },
      { name: "Triton GLS AT 4x2", price: "Rp 367 Juta" },
      { name: "Triton GLS AT 4x4", price: "Rp 427 Juta" },
    ],
    description: "Triton — Pickup tangguh dengan Super Select 4WD dan mesin 2.4L Turbo Diesel 181 PS. Jet Thrust Fin aerodinamis, Hill Descent Control, dan Rear Differential Lock siap menaklukkan segala medan.",
    warranty: "3 Tahun / 100.000 km",
  },
  {
    slug: "l300",
    name: "L300",
    category: "Pickup",
    tagline: "The Legend Lives On",
    price: "Mulai Rp 233 Juta",
    priceNum: 233,
    image: "/images/l300.png",
    heroImage: "/images/l300.png",
    engine: "2.5L Diesel",
    transmission: "5MT",
    seats: "2 Penumpang",
    power: "80 PS",
    torque: "189 Nm",
    fuel: "Diesel",
    topSpeed: "130 km/h",
    acceleration: "18 detik",
    features: [
      "Mesin Diesel Tangguh",
      "Beban Muat 1.050 kg",
      "Suspensi Daun",
      "Power Steering",
      "AC Double Blower",
      "Kelistrikan 12V",
      "Ban Luas 185/R14",
      "Pintu Samping Sliding",
      "Rangka Kokoh",
      "Harga Terjangkau",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "2.5L Diesel" },
      { icon: "fuel", label: "BBM", value: "14.8 km/L" },
      { icon: "seat", label: "Kapasitas", value: "2 Penumpang" },
      { icon: "safety", label: "Payload", value: "1.050 kg" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Gunmetal Gray", hex: "#5a5a5a" },
    ],
    variants: [
      { name: "L300 Flat Deck", price: "Rp 233 Juta" },
      { name: "L300 Box", price: "Rp 245 Juta" },
    ],
    description: "L300 — Pickup komersial legendaris yang handal dan ekonomis. Muat beban hingga 1.050 kg dengan konsumsi BBM irit. Pilihan usaha kecil menengah yang sudah terbukti selama puluhan tahun.",
    warranty: "2 Tahun / 50.000 km",
  },
  {
    slug: "outlander-phev",
    name: "Outlander PHEV",
    category: "SUV",
    tagline: "Drive Beyond Limits",
    price: "Mulai Rp 1,2 M",
    priceNum: 1200,
    image: "/images/outlander.png",
    heroImage: "/images/outlander.png",
    engine: "2.0L Hybrid PHEV",
    transmission: "CVT",
    seats: "7 Penumpang",
    power: "213 PS (Combined)",
    torque: "350 Nm (Combined)",
    fuel: "Hybrid (Bensin + Listrik)",
    topSpeed: "170 km/h",
    acceleration: "8.5 detik",
    features: [
      "Plug-in Hybrid Electric Vehicle",
      "EV Mode 87 km",
      "Super All Wheel Control",
      "Multi Around Monitor",
      "Forward Collision Mitigation",
      "10.8\" Head Unit",
      "Bose Premium Sound System",
      "Dual Zone Auto AC",
      "Power Tailgate",
      "Remote Climate Control via App",
    ],
    highlights: [
      { icon: "engine", label: "Mesin", value: "2.0L PHEV" },
      { icon: "fuel", label: "EV Range", value: "87 km" },
      { icon: "seat", label: "Kapasitas", value: "7 Penumpang" },
      { icon: "safety", label: "Safety", value: "5★ ASEAN NCAP" },
    ],
    colors: [
      { name: "White Diamond", hex: "#f5f5f0" },
      { name: "Jet Black Mica", hex: "#1a1a1a" },
      { name: "Brilliant Blue", hex: "#2d5da1" },
      { name: "Red Diamond", hex: "#8b1a1a" },
    ],
    variants: [
      { name: "Outlander PHEV Exceed", price: "Rp 1,2 Miliar" },
      { name: "Outlander PHEV Ultimate", price: "Rp 1,3 Miliar" },
    ],
    description: "Outlander PHEV — SUV hybrid plug-in premium dengan teknologi ramah lingkungan. Jarak tempuh EV 87 km, Super All Wheel Control, Bose Sound System, dan kabin mewah 7 penumpang. Masa depan berkendara dimulai di sini.",
    warranty: "5 Tahun / 100.000 km (Battery 10 Tahun)",
  },
];

export function getCarBySlug(slug: string): CarModel | undefined {
  return cars.find((car) => car.slug === slug);
}

export function getRelatedCars(car: CarModel): CarModel[] {
  return cars.filter((c) => c.category === car.category && c.slug !== car.slug).slice(0, 3);
}
